   # Gal Vakeselman: This is a workflow to test deployment status 

name: Test deployment from master

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  DBT_PROFILE_TARGET: prod
  DBT_PROFILE_SNOWFLAKE_ACCOUNT: ''
  DBT_PROFILE_USER: ''
  DBT_PROFILE_PASSWORD: ''
  DBT_PROFILE_ROLE: ''
  DBT_PROFILE_DB: ''
  DBT_PROFILE_SCHEMA: ''
  DBT_PROFILE_WH: ''
  

jobs:
  prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
      
      - name: Install Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install DBT
        run: |
          python -m pip install --upgrade pip
          pip install dbt-snowflake
  
      
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, prod!
